version: '3'

services:
  common_db:
    image: akoller/low-memory-mysql
    volumes:
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "8033:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=Cn0gh0wtyny0
      - MYSQL_ROOT_HOST=%
  fuel_optimization:
    image: 127.0.0.1:5000/fuel_optimization
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  fuel_stations:
    image: 127.0.0.1:5000/fuel_stations
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  fuel_stations_core:
    entrypoint: /wait-for-it.sh common_db:3306 -t 0 --
    image: 127.0.0.1:5000/fuel_stations_core
    command: ['dotnet', 'Fleet.FuelStationsCore.dll']
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ConnectionStrings:FuelStations=Server=common_db;Port=3306;Database=FuelStations;Uid=root;Pwd=Cn0gh0wtyny0;old guids=true;
    depends_on:
      - common_db
  transportation_management:
    entrypoint: /wait-for-it.sh common_db:3306 -t 0 --
    image: 127.0.0.1:5000/transportation_management
    command: ['dotnet', 'Fleet.TransportationManagement.dll']
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ConnectionStrings:TransportationManagement=Server=common_db;Port=3306;Database=TransportationManagement;Uid=root;Pwd=Cn0gh0wtyny0;old guids=true;
    depends_on:
      - common_db
  ui:
    image: 127.0.0.1:5000/ui
    volumes:
      - 'static-content:/app/build'
    environment:
      - NODE_ENV=production
      - REACT_APP_FM_URL=https://167.71.33.134/fm
      - REACT_APP_FS_URL=https://167.71.33.134/fs
      - REACT_APP_TM_URL=https://167.71.33.134/tm
  gateway:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - './nginx/development.conf:/etc/nginx/env/development.conf'

      - './nginx/production.conf:/etc/nginx/env/production.conf'
      - 'static-content:/usr/share/nginx/static'
    environment:
      - NGINX_HOST=167.71.33.134
      - NGINX_EXT_SSL_PORT=443

volumes:
  static-content:
